# Generated by Django 3.2 on 2021-07-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('item_status', models.CharField(choices=[('available', 'available'), ('bought', 'bought'), ('pending', 'pending'), ('not available', 'not available')], default='available', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
